/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Yosef Febrianes
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        regionButton = new javax.swing.JButton();
        locationsButton = new javax.swing.JButton();
        jobsButton = new javax.swing.JButton();
        employeesButton = new javax.swing.JButton();
        departementsButton = new javax.swing.JButton();
        contriesButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 51));
        jLabel4.setFont(new java.awt.Font("Courier New", 1, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Human Resources Schema");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1330, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yosef Febrianes\\Downloads\\icons8-exit-sign-46.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, 50, -1));

        regionButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        regionButton.setText("REGIONS");
        regionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(regionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 210, 50));

        locationsButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        locationsButton.setText("LOCATIONS");
        locationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(locationsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 210, 50));

        jobsButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jobsButton.setText("JOBS");
        jobsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jobsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 560, 210, 50));

        employeesButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        employeesButton.setText("EMPLOYEES");
        employeesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(employeesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 560, 210, 50));

        departementsButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        departementsButton.setText("DEPARTEMENTS");
        departementsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departementsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(departementsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 560, 210, 50));

        contriesButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        contriesButton.setText("CONTRIES");
        contriesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contriesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(contriesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 210, 50));

        jLabel2.setBackground(new java.awt.Color(255, 255, 51));
        jLabel2.setFont(new java.awt.Font("Corbel Light", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("KP_UKSW_Batch2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 300, 1370, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 51));
        jLabel3.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PT. Metrodata Electronics, Tbk");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 1370, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 51));
        jLabel5.setFont(new java.awt.Font("Corbel Light", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("tugas akhir pekan 2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 1360, -1));

        jButton2.setText("back to login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yosef Febrianes\\Desktop\\TugasAkhirPekan2\\qaz1.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void regionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regionButtonActionPerformed
        // TODO add your handling code here:
        RegionView rv = new RegionView();
        rv.setVisible(true);
    }//GEN-LAST:event_regionButtonActionPerformed

    private void locationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationsButtonActionPerformed
        // TODO add your handling code here:
        LocationView lv = new LocationView();
        lv.setVisible(true);
    }//GEN-LAST:event_locationsButtonActionPerformed

    private void jobsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobsButtonActionPerformed
        // TODO add your handling code here:
//        JobView rv = new JobView();
//        rv.setVisible(true);
    }//GEN-LAST:event_jobsButtonActionPerformed

    private void employeesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeesButtonActionPerformed
        // TODO add your handling code here:
        EmployeeView ev = new EmployeeView();
        ev.setVisible(true);
    }//GEN-LAST:event_employeesButtonActionPerformed

    private void departementsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departementsButtonActionPerformed
        // TODO add your handling code here:
//        DepartmentView rv = new DepartmentView();
//        rv.setVisible(true);
    }//GEN-LAST:event_departementsButtonActionPerformed

    private void contriesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contriesButtonActionPerformed
        // TODO add your handling code here:
//        CountryView rv = new CountryView();
//        rv.setVisible(true);
    }//GEN-LAST:event_contriesButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Loginview lv = new Loginview();
        lv.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton contriesButton;
    private javax.swing.JButton departementsButton;
    private javax.swing.JButton employeesButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jobsButton;
    private javax.swing.JButton locationsButton;
    private javax.swing.JButton regionButton;
    // End of variables declaration//GEN-END:variables
}
