/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.RegionController;
import controllers.icontrollers.IRegionController;
import daos.RegionDAO;
import daos.idaos.IRegionDAO;
import javax.swing.DefaultButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import models.Region;
import tools.HibernateUtil;

/**
 *
 * @author Yosef Febrianes
 */
public class RegionView extends javax.swing.JFrame {

    /**
     * Creates new form RegionView
     */
    public RegionView() {
        initComponents();
        getAll();
    }

    void getAll() {
        HibernateUtil sessionFactory = new HibernateUtil();
        IRegionController irc = new RegionController(sessionFactory.getSessionFactory());
        IRegionDAO irdao = new RegionDAO(sessionFactory.getSessionFactory());

//        Region r = new Region();
        DefaultTableModel dt;
        DefaultButtonModel db;
        Object[] baris = {"No", "Region ID", "Region Name"};
        dt = new DefaultTableModel(null, baris);

        regionIdField.setEditable(true);
        regionTable.setModel(dt);
        regionIdField.setText("");
        regionNameField.setText("");

        try {
            int i = 1;
            for (Region regiong : irdao.getAll()) {
//                System.out.println(regiong.getRegionId() + " || " + regiong.getRegionName());

                String NO = Integer.toString(i);
                String ID = regiong.getId();
                String NM = regiong.getName();
                String bt = refreshButton + "";

                String[] data = {NO, ID, NM, bt};
                dt.addRow(data);
                i++;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan!\n" + e, "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void search() {
        HibernateUtil sessionFactory = new HibernateUtil();
        IRegionController irc = new RegionController(sessionFactory.getSessionFactory());
        IRegionDAO irdao = new RegionDAO(sessionFactory.getSessionFactory());
        Region regionn = new Region(searchButton.getText());

//        Region r = new Region();
        DefaultTableModel dt;
        DefaultButtonModel db;

        Object[] baris = {"Region ID", "Region Name"};
        dt = new DefaultTableModel(null, baris);
        regionTable.setModel(dt);

        try {
            for (Region regiong : irdao.search(searchField.getText())) {
//                System.out.println(regiong.getRegionId() + " || " + regiong.getRegionName());

                String ID = regiong.getId();
                String NM = regiong.getName();

                String[] data = {ID, NM};
                dt.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan!\n" + e, "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        regionIdField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        regionNameField = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        insertButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        regionTable = new javax.swing.JTable();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(249, 255, 255));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        jLabel5.setText("Region Table");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 11, 286, 81);

        regionIdField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        regionIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regionIdFieldActionPerformed(evt);
            }
        });
        regionIdField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                regionIdFieldKeyReleased(evt);
            }
        });
        jPanel1.add(regionIdField);
        regionIdField.setBounds(10, 129, 286, 26);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Region ID : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 103, 87, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Region Name : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 178, 111, 20);

        regionNameField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        regionNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regionNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(regionNameField);
        regionNameField.setBounds(10, 204, 291, 26);

        updateButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(updateButton);
        updateButton.setBounds(10, 248, 93, 29);

        insertButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        insertButton.setText("INSERT");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });
        jPanel1.add(insertButton);
        insertButton.setBounds(109, 248, 93, 29);

        deleteButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton);
        deleteButton.setBounds(208, 248, 93, 29);

        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        jPanel1.add(searchField);
        searchField.setBounds(103, 306, 126, 26);

        searchButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yosef Febrianes\\Downloads\\icons8-search-15.png")); // NOI18N
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(searchButton);
        searchButton.setBounds(239, 306, 26, 26);

        refreshButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yosef Febrianes\\Downloads\\icons8-refresh-15.png")); // NOI18N
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        jPanel1.add(refreshButton);
        refreshButton.setBounds(275, 306, 26, 26);

        regionTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        regionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        regionTable.setColumnSelectionAllowed(true);
        regionTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        regionTable.setRequestFocusEnabled(false);
        regionTable.setRowMargin(2);
        regionTable.setVerifyInputWhenFocusTarget(false);
        regionTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regionTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(regionTable);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(320, 10, 443, 380);

        exitButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yosef Febrianes\\Downloads\\icons8-exit-sign-20.png")); // NOI18N
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton);
        exitButton.setBounds(260, 350, 40, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regionIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regionIdFieldActionPerformed

    }//GEN-LAST:event_regionIdFieldActionPerformed

    private void regionIdFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regionIdFieldKeyReleased
        // TODO add your handling code here:
        int position = regionIdField.getCaretPosition();
        regionIdField.setText(regionIdField.getText().toUpperCase());
        regionIdField.setCaretPosition(position);
    }//GEN-LAST:event_regionIdFieldKeyReleased

    private void regionNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regionNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regionNameFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        HibernateUtil sessionFactory = new HibernateUtil();
        IRegionController irc = new RegionController(sessionFactory.getSessionFactory());
//        Region region = new Region(regionIdField.getText(), regionNameField.getText());

        JOptionPane.showMessageDialog(null, irc.update(regionIdField.getText(), regionNameField.getText()));
        regionIdField.setText("");
        regionNameField.setText("");
        getAll();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed

        HibernateUtil sessionFactory = new HibernateUtil();
        IRegionController irc = new RegionController(sessionFactory.getSessionFactory());
        Region region = new Region(regionIdField.getText(), regionNameField.getText());

        //    public String insert (String regionId, String regionName);
        JOptionPane.showMessageDialog(null, irc.insert(regionIdField.getText(), regionNameField.getText()));
        SwingUtilities.updateComponentTreeUI(insertButton);
        regionIdField.setText("");
        regionNameField.setText("");
        getAll();
    }//GEN-LAST:event_insertButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        HibernateUtil sessionFactory = new HibernateUtil();
        IRegionController irc = new RegionController(sessionFactory.getSessionFactory());
        Region region = new Region(regionIdField.getText(), regionNameField.getText());

        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Delete", "Title on Box", dialogButton);
        if (dialogResult == 0) {
            Region regionn = new Region(regionIdField.getText(), regionNameField.getText());
            //        confirmDelete("wkwk");

            JOptionPane.showMessageDialog(null, irc.delete(regionIdField.getText()));
            regionIdField.setText("");
            regionNameField.setText("");
            getAll();
        } else {
            getAll();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        search();
        searchField.setText("");
    }//GEN-LAST:event_searchButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        getAll();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void regionTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regionTableMouseClicked
        HibernateUtil sessionFactory = new HibernateUtil();
        IRegionController irc = new RegionController(sessionFactory.getSessionFactory());
        Region region = new Region(regionIdField.getText(), regionNameField.getText());

        JTable source = (JTable) evt.getSource();
        regionIdField.setEditable(false);

        int i = regionTable.getSelectedRow();
        regionIdField.setText(source.getModel().getValueAt(i, 1) + "");
        regionNameField.setText(source.getModel().getValueAt(i, 2) + "");
    }//GEN-LAST:event_regionTableMouseClicked

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegionView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton insertButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTextField regionIdField;
    private javax.swing.JTextField regionNameField;
    private javax.swing.JTable regionTable;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
